#!/bin/bash

## Files and cmd
EWW="eww -c $HOME/.config/hypr/themes/garden/eww/"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
${EWW} open-many sidebar notifications
${EWW} open bar0
${EWW} open bar1
${EWW} open bar2
${EWW} open bar3
# ${EWW} open bar4
# ${EWW} open bar5

NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
for i in "${!NB_MONITORS[@]}"; do
    ${EWW} open bar$i
    [[ $i == 0 ]] && ${EWW} open-many sidebar notifications
done
