#! /bin/bash

#define icons for workspaces 1-9
#icontheme=$(geticons -U)
icontheme=$(grep "gtk-icon-theme-name" "$HOME"/.config/gtk-3.0/settings.ini | cut --delimiter="=" -f 2)

workspaces() {
#echo $1
if [[ ${1:0:14} == "activewindow>>" ]]; then #set focused workspace
    winInfo=${1:14}
    class="lol"
    # class="${winInfo/,*/}"
    export title=${winInfo/,/ \| }
    [[ $title == " | " ]] && unset title
    export iconpath=$(geticons "$class" -s 24 -c 1 -t "$icontheme" | head -n 1)
    echo $title
fi
}

module() {
#output eww widget
echo 	"(box \
                :orientation \"h\" \
                :halign \"start\" \
                :space-evenly false \
                (image \
                    :class \"app-icon\" \
                    :path \"$iconpath\" \
                    :image-width \"36\") \
                (label \
                    :class \"app-name\" \
                    :limit-width \"150\" \
                    :text \"$title\" \
                    :tooltip \"$title\"))"
}

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
  workspaces "$event"
  module
done
