#! /bin/bash

#define icons for workspaces 9-16
#ic=(0     輸  " " " " )
ic=(0   󰨞     )

export sp="a"

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | awk '{print $3}'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep -B 4 "focused: yes" | awk 'NR==1{print $3}'); do 
  export f"$num"="$num"
  export fnum=f"$num"
  export mon=$(hyprctl monitors | grep -B 2 "\($num\)" | awk 'NR==1{print $2}')
done

workspaces() {
if [[ ${1:0:9} == "workspace" ]] && [[ ${1:11} != "special" ]]; then #set focused workspace
  unset -v "$fnum" 
  num=${1:11:12}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:10} == "focusedmon" ]]; then #set focused workspace following monitor focus change
  unset -v "$fnum"
  string=${1:12:13}
  num=${string##*,}
  export mon=${string/,*/}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:13} == "moveworkspace" ]] && [[ ${1##*,} == "$mon" ]]; then #Set focused workspace following swapactiveworkspace
  unset -v "$fnum"
  string=${1:15:16}
  num=${string/,*/}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17:18}
  export o"$num"="$num"
  export onum=o"$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18:19}
  unset -v o"$num"
fi

}
module() {
#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"v\" :spacing 5 :space-evenly \"false\" :valign \"center\"	\
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 9\'\" :onrightclick \"hyprctl dispatch workspace 9 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o9$sp$f9\" \"${ic[1]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 10\'\" :onrightclick \"hyprctl dispatch workspace 10 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o10$sp$f10\" \"${ic[2]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 11\'\" :onrightclick \"hyprctl dispatch workspace 11 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o11$sp$f11\" \"${ic[3]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 12\'\" :onrightclick \"hyprctl dispatch workspace 12 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o12$sp$f12\" \"${ic[4]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 13\'\" :onrightclick \"hyprctl dispatch workspace 13 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o13$sp$f13\" \"${ic[5]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 14\'\" :onrightclick \"hyprctl dispatch workspace 14 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o14$sp$f14\" \"${ic[6]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 15\'\" :onrightclick \"hyprctl dispatch workspace 15 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o15$sp$f15\" \"${ic[7]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 16\'\" :onrightclick \"hyprctl dispatch workspace 16 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"0mar 0$sp$o16$sp$f16\" \"${ic[8]}\") \
          )\
        )" | tee ~/.ewwt
}

module

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
module
done
