#! /bin/bash

#define icons for workspaces 9-16
#ic=(0     輸  " " " " )
ic=(0 󰣡 󰣥 󰣧 󰣤 󰣢 󰣣 󰣦 󰕞)

export sp="a"

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | awk '{print $3}'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep -B 4 "focused: yes" | awk 'NR==1{print $3}'); do 
  export f"$num"="$num"
  export fnum=f"$num"
  export mon=$(hyprctl monitors | grep -B 2 "\($num\)" | awk 'NR==1{print $2}')
done

workspaces() {
if [[ ${1:0:9} == "workspace" ]] && [[ ${1:11} != "special" ]]; then #set focused workspace
  unset -v "$fnum" 
  num=${1:11:12}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:10} == "focusedmon" ]]; then #set focused workspace following monitor focus change
  unset -v "$fnum"
  string=${1:12:13}
  num=${string##*,}
  export mon=${string/,*/}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:13} == "moveworkspace" ]] && [[ ${1##*,} == "$mon" ]]; then #Set focused workspace following swapactiveworkspace
  unset -v "$fnum"
  string=${1:15:16}
  num=${string/,*/}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17:18}
  export o"$num"="$num"
  export onum=o"$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18:19}
  unset -v o"$num"
fi
}
module() {
#output eww widget
echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
          (box	:class \"works\"	:orientation \"v\" :spacing 5 :space-evenly \"false\" :valign \"center\"	\
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 31\'\" :onrightclick \"hyprctl dispatch workspace 31 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o31$sp$f31\" \"${ic[1]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 32\'\" :onrightclick \"hyprctl dispatch workspace 32 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o32$sp$f32\" \"${ic[2]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 33\'\" :onrightclick \"hyprctl dispatch workspace 33 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o33$sp$f33\" \"${ic[3]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 34\'\" :onrightclick \"hyprctl dispatch workspace 34 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o34$sp$f34\" \"${ic[4]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 35\'\" :onrightclick \"hyprctl dispatch workspace 35 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o35$sp$f35\" \"${ic[5]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 36\'\" :onrightclick \"hyprctl dispatch workspace 36 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o36$sp$f36\" \"${ic[6]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 37\'\" :onrightclick \"hyprctl dispatch workspace 37 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o37$sp$f37\" \"${ic[7]}\") \
              (button :onclick \"hyprctl dispatch exec \'~/.config/hypr/scripts/workspace.sh 38\'\" :onrightclick \"hyprctl dispatch workspace 38 && $HOME/.config/hypr/scripts/default_app.sh\" :class \"_0mar _0$sp$o38$sp$f38\" \"${ic[8]}\") \
          )\
        )" | tee ~/.ewwt
}

module

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
module
done

